apiVersion: v1
kind: ConfigMap
metadata:
  name: smartpark-config
  namespace: smartpark
data:
  SPRING_DATA_MONGODB_URI: "mongodb://smartpark-mongodb:27017/smartpark_db"
  SPRING_DATA_MONGODB_DATABASE: "smartpark_db"
  SERVER_PORT: "8082"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_AUTOCONFIGURE_EXCLUDE: "org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration"
